// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectToNode(arg1) {
  return window['go']['main']['App']['ConnectToNode'](arg1);
}

export function CreateAccount(arg1) {
  return window['go']['main']['App']['CreateAccount'](arg1);
}

export function ExecuteConsoleCommand(arg1) {
  return window['go']['main']['App']['ExecuteConsoleCommand'](arg1);
}

export function ExportAccount(arg1, arg2) {
  return window['go']['main']['App']['ExportAccount'](arg1, arg2);
}

export function GetAccounts() {
  return window['go']['main']['App']['GetAccounts']();
}

export function GetBalance(arg1) {
  return window['go']['main']['App']['GetBalance'](arg1);
}

export function GetMinerSetupInstructions() {
  return window['go']['main']['App']['GetMinerSetupInstructions']();
}

export function GetMiningInfo() {
  return window['go']['main']['App']['GetMiningInfo']();
}

export function GetNetworkInfo() {
  return window['go']['main']['App']['GetNetworkInfo']();
}

export function GetTransactions(arg1) {
  return window['go']['main']['App']['GetTransactions'](arg1);
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWalletConfig() {
  return window['go']['main']['App']['GetWalletConfig']();
}

export function GetWalletInfo() {
  return window['go']['main']['App']['GetWalletInfo']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportAccount(arg1, arg2) {
  return window['go']['main']['App']['ImportAccount'](arg1, arg2);
}

export function SaveWalletConfig(arg1) {
  return window['go']['main']['App']['SaveWalletConfig'](arg1);
}

export function SendTransaction(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SendTransaction'](arg1, arg2, arg3, arg4);
}

export function StartMining() {
  return window['go']['main']['App']['StartMining']();
}

export function StopMining() {
  return window['go']['main']['App']['StopMining']();
}
