version: '3.8'

services:
  # Q Geth Node (Testnet)
  qgeth-testnet:
    build:
      context: .
      dockerfile: Dockerfile
    image: qgeth:latest
    container_name: qgeth-testnet
    ports:
      - "8545:8545"    # HTTP RPC
      - "8546:8546"    # WebSocket
      - "30303:30303"  # P2P TCP
      - "30303:30303/udp"  # P2P UDP
    volumes:
      - qgeth_data:/opt/qgeth/data
      - ./configs:/opt/qgeth/configs:ro
    environment:
      - NETWORK=testnet
      - CHAIN_ID=73235
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - qgeth-network

  # Q Geth Node (Planck Network)
  qgeth-planck:
    build:
      context: .
      dockerfile: Dockerfile
    image: qgeth:latest
    container_name: qgeth-planck
    ports:
      - "8551:8545"    # HTTP RPC
      - "8552:8546"    # WebSocket
      - "30307:30303"  # P2P TCP
      - "30307:30303/udp"  # P2P UDP
    volumes:
      - qgeth_planck_data:/opt/qgeth/data
      - ./configs:/opt/qgeth/configs:ro
    environment:
      - NETWORK=planck
      - CHAIN_ID=73237
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8545"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - qgeth-network

  # Q Geth Node with Mining (Testnet)
  qgeth-miner:
    build:
      context: .
      dockerfile: Dockerfile
    image: qgeth:latest
    container_name: qgeth-miner
    ports:
      - "8547:8545"    # HTTP RPC (different port to avoid conflicts)
      - "8548:8546"    # WebSocket
      - "30304:30303"  # P2P TCP
      - "30304:30303/udp"  # P2P UDP
    volumes:
      - qgeth_miner_data:/opt/qgeth/data
      - ./configs:/opt/qgeth/configs:ro
    environment:
      - NETWORK=testnet
      - CHAIN_ID=73235
      - MINING=true
      - MINER_ETHERBASE=0x742d35C6C4e6d8de6f10E7FF75DD98dd25b02C3A
    command: >
      geth
      --datadir /opt/qgeth/data
      --networkid 73235
      --port 30303
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.corsdomain "*"
      --http.api "eth,net,web3,personal,admin,txpool,miner,qmpow"
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.origins "*"
      --ws.api "eth,net,web3,personal,admin,txpool,miner,qmpow"
      --maxpeers 25
      --verbosity 1
      --mine
      --miner.threads 0
      --miner.etherbase 0x742d35C6C4e6d8de6f10E7FF75DD98dd25b02C3A
    restart: unless-stopped
    profiles:
      - mining
    networks:
      - qgeth-network

  # Development Node (Isolated)
  qgeth-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: qgeth:latest
    container_name: qgeth-dev
    ports:
      - "8549:8545"    # HTTP RPC
      - "8550:8546"    # WebSocket
      - "30305:30303"  # P2P TCP
      - "30305:30303/udp"  # P2P UDP
    volumes:
      - qgeth_dev_data:/opt/qgeth/data
      - ./configs:/opt/qgeth/configs:ro
    environment:
      - NETWORK=dev
      - CHAIN_ID=73234
    command: >
      geth
      --datadir /opt/qgeth/data
      --networkid 73234
      --port 30303
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.corsdomain "*"
      --http.api "eth,net,web3,personal,admin,txpool,miner,qmpow,debug"
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.origins "*"
      --ws.api "eth,net,web3,personal,admin,txpool,miner,qmpow,debug"
      --maxpeers 25
      --verbosity 1
      --mine
      --miner.threads 0
      --miner.etherbase 0x742d35C6C4e6d8de6f10E7FF75DD98dd25b02C3A
      --nodiscover
      --syncmode full
    restart: unless-stopped
    profiles:
      - dev
    networks:
      - qgeth-network

volumes:
  qgeth_data:
    driver: local
  qgeth_planck_data:
    driver: local
  qgeth_miner_data:
    driver: local
  qgeth_dev_data:
    driver: local

networks:
  qgeth-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24 