// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectToNode(arg1:string):Promise<void>;

export function CreateAccount(arg1:string):Promise<string>;

export function ExecuteConsoleCommand(arg1:string):Promise<string>;

export function ExportAccount(arg1:string,arg2:string):Promise<string>;

export function GetAccounts():Promise<Array<main.Account>>;

export function GetBalance(arg1:string):Promise<string>;

export function GetMinerSetupInstructions():Promise<Record<string, any>>;

export function GetMiningInfo():Promise<main.MiningInfo>;

export function GetNetworkInfo():Promise<main.NetworkInfo>;

export function GetTransactions(arg1:string):Promise<Array<main.Transaction>>;

export function GetVersion():Promise<string>;

export function GetWalletConfig():Promise<main.WalletConfig>;

export function GetWalletInfo():Promise<Record<string, any>>;

export function Greet(arg1:string):Promise<string>;

export function ImportAccount(arg1:string,arg2:string):Promise<main.Account>;

export function SaveWalletConfig(arg1:main.WalletConfig):Promise<void>;

export function SendTransaction(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartMining():Promise<void>;

export function StopMining():Promise<void>;
